# User Settings | Edit there as per required

title: clojure-korea
url: "http://clojure.kr"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    clojure <span class="faded">korea</span>

email: clojure.kr@gmail.com
author: clojure-korea
# This description will show up in google search results
# (for index page) etc.
#description: > # this means to ignore newlines until "baseurl:"
#  클로저 코리아에서 운영하는 블로그 입니다.</br>

# This will what will show against &copy; in the footer
copyright: clojure-korea
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    반갑습니다.

permalink: /:title

# Comments are powered by disqus
comments: true
disqus: clojure-kr

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    <a href="https://www.facebook.com/groups/defnclojure/">페이스북 그룹: defnclojure</a>

about_footer: true

#twitter_username: dalzony
github_username: clojure-korea
facebook_id: groups/defnclojure

favicon: true
favicon_location: "http://clojure.org/images/clojure-logo-icon-32.png"

profile_picture: images/clojure-logo.png
no-profile: images/no-profile.gif
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/clojurekr.png" # This will show in facebook thumbnails
twitter_image: "" # This will show in twitter cards


####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass
    cache: false

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
