# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: (clojure korea)
email: clojure.kr at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  클로저 코리아에서 운영하는 블로그 입니다.</br>
  FB : www.facebook.com/groups/defnclojure

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clojure.kr" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  clojure-korea

# Build settings
# markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:title
